### ISSUE TITLE
Your application succesfully build and deploy. but...

### ISSUE THREAD

**Issue by sevketk** [HelloZB/QtAndroidFTDI#2]
Your application succesfully build and deploy. but I only encountered the icon of the app and a blank screen underneath. 
I get only one warning.

```
Warning: QML import could not be resolved in any of the import paths: QtQuick.Extras.Private.CppUtils
Warning: QML import could not be resolved in any of the import paths: QtQuick.Extras.Private.CppUtils
```
I use graddle 4.0.1,  QT 5.15, android build sdk:android-29,  target Sdk :22, minimum sdk: not set

**Comment by sevketk** [comment]
So application output have alots of error.
```
I         : power log dlsym ok
I zygote  : Late-enabling -Xcheck:jni
D ActivityThread: ActivityThread,attachApplication
D HwFLClassLoader: get used feature list :/feature/used-list failed!
D HwFLClassLoader: USE_FEATURE_LIST had not init!
I HwApiCacheMangerEx: apicache mCurPackageName=ua.pp.varto uptimes=1083048
E asset   : createFromFile(): lock file /data/resource-cache/product@overlay@frameworkResOverlay.apk@idmap.
E asset   : createFromFile(): lock file /data/resource-cache/product@overlay@frameworkResOverlay.apk@idmap.
W ResourceType: Found multiple library tables, ignoring...
I HwApiCacheMangerEx: apicache oUid null
I HwApiCacheMangerEx: apicache volumes null
I HwApiCacheMangerEx: apicache path=/storage/emulated/0 state=mounted key=ua.pp.varto#10111#256
I HwApiCacheMangerEx: apicache oUid 10111
I HwApiCacheMangerEx: apicache volumes null
I HwApiCacheMangerEx: apicache path=/storage/emulated/0 state=mounted key=ua.pp.varto#10111#0
I HwApiCacheMangerEx: apicache async read begin packageName=ua.pp.varto userid=0
I HwApiCacheMangerEx: apicache pi null
I HwApiCacheMangerEx: apicache pi null
I HwApiCacheMangerEx: apicache pi null
E Minikin : Could not get cmap table size!
I HwApiCacheMangerEx: apicache pi null
I HwApiCacheMangerEx: apicache oUid null
E asset   : createFromFile(): lock file /data/resource-cache/product@overlay@frameworkResOverlay.apk@idmap.
E asset   : createFromFile(): lock file /data/resource-cache/product@overlay@frameworkResOverlay.apk@idmap.
W ResourceType: Found multiple library tables, ignoring...
I HwApiCacheMangerEx: apicache async read finished packageName=ua.pp.varto userid=0 totalus=37121
E MemoryLeakMonitorManager: MemoryLeakMonitor.jar is not exist!
I HwCust  : Constructor found for class android.app.HwCustActivityImpl
D HwCust  : Create obj success use class android.app.HwCustActivityImpl
V HwPolicyFactory: : success to get AllImpl object and return....
V ActivityThread: ActivityThread,callActivityOnCreate
V HwWidgetFactory: : successes to get AllImpl object and return....
W ResourceType: Invalid package identifier when getting bag for resource number 0x00000000
E Qt      : Can't create main activity
E Qt      : android.content.res.Resources$NotFoundException: String array resource ID #0x0
E Qt      : 	at android.content.res.Resources.getStringArray(Resources.java:648)
E Qt      : 	at android.content.res.HwResources.getStringArray(HwResources.java:497)
E Qt      : 	at org.qtproject.qt5.android.bindings.QtLoader.startApp(QtLoader.java:423)
E Qt      : 	at org.qtproject.qt5.android.bindings.QtActivityLoader.onCreate(QtActivityLoader.java:166)
E Qt      : 	at org.qtproject.qt5.android.bindings.QtActivity.onCreateHook(QtActivity.java:266)
E Qt      : 	at org.qtproject.qt5.android.bindings.QtActivity.onCreate(QtActivity.java:273)
E Qt      : 	at android.app.Activity.performCreate(Activity.java:7383)
E Qt      : 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
E Qt      : 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3256)
E Qt      : 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3411)
E Qt      : 	at android.app.ActivityThread.-wrap12(Unknown Source:0)
E Qt      : 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1994)
E Qt      : 	at android.os.Handler.dispatchMessage(Handler.java:108)
E Qt      : 	at android.os.Looper.loop(Looper.java:166)
E Qt      : 	at android.app.ActivityThread.main(ActivityThread.java:7529)
E Qt      : 	at java.lang.reflect.Method.invoke(Native Method)
E Qt      : 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
E Qt      : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
D HwGalleryCacheManagerImpl: mIsEffect:false
D CubicBezierInterpolator: CubicBezierInterpolator  mControlPoint1x = 0.23, mControlPoint1y = 0.06, mControlPoint2x = 0.09, mControlPoint2y = 0.97
D CubicBezierInterpolator: CubicBezierInterpolator  mControlPoint1x = 0.6, mControlPoint1y = 0.9, mControlPoint2x = 0.8, mControlPoint2y = 1.0
V BoostFramework: /system/framework/QPerformance.jar be checked !
V BoostFramework: mAcquireFunc method = public int com.qualcomm.qti.Performance.perfLockAcquire(int,int[])
V BoostFramework: mReleaseFunc method = public int com.qualcomm.qti.Performance.perfLockRelease()
E BoostFramework: BoostFramework() : Exception_1 = java.lang.NoSuchMethodException: perfLockAcquireTouch [class android.view.MotionEvent, class android.util.DisplayMetrics, int, class [I]
E linker  : library "/system/lib/libqti_performance.so" ("/system/lib/libqti_performance.so") needed or dlopened by "/system/lib/libnativeloader.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="", permitted_paths="/data:/mnt/expand"]
V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@f87d706
D CubicBezierInterpolator: CubicBezierInterpolator  mControlPoint1x = 0.23, mControlPoint1y = 0.06, mControlPoint2x = 0.09, mControlPoint2y = 0.97
D CubicBezierInterpolator: CubicBezierInterpolator  mControlPoint1x = 0.6, mControlPoint1y = 0.9, mControlPoint2x = 0.8, mControlPoint2y = 1.0
V BoostFramework: /system/framework/QPerformance.jar be checked !
V BoostFramework: mAcquireFunc method = public int com.qualcomm.qti.Performance.perfLockAcquire(int,int[])
V BoostFramework: mReleaseFunc method = public int com.qualcomm.qti.Performance.perfLockRelease()
E BoostFramework: BoostFramework() : Exception_1 = java.lang.NoSuchMethodException: perfLockAcquireTouch [class android.view.MotionEvent, class android.util.DisplayMetrics, int, class [I]
E linker  : library "/system/lib/libqti_performance.so" ("/system/lib/libqti_performance.so") needed or dlopened by "/system/lib/libnativeloader.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="", permitted_paths="/data:/mnt/expand"]
V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@4fe91c7
D ActivityThread: add activity client record, r= ActivityRecord{2110b53 token=android.os.BinderProxy@ffad773 {ua.pp.varto/org.qtproject.qt5.android.bindings.QtActivity}} token= android.os.BinderProxy@ffad773
I HwSecImmHelper: mSecurityInputMethodService is null
D OpenGLRenderer:   HWUI Binary is  disabled
D OpenGLRenderer: HWUI GL Pipeline
I PressGestureDetector: onAttached begin
I PressGestureDetector: onAttached end
I PressGestureDetector: HiTouch restricted: AboardArea.
I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 06/25/18, 00d0768, Ie4790512f3
W WindowDecorActionBar: should not do the transition or the transition anim is null or it is running or the mContainer view is null or mContainer view hasn't been drawn to screen
E HwResourcesImpl: readDefaultConfig : FileNotFoundException
I iGraphics: [0020080c] pn: ua.pp.varto, p: 9746
W RenderThread: type=1400 audit(0.0:270): avc: denied { search } for name="kgsl-3d0" dev="sysfs" ino=21562 scontext=u:r:untrusted_app_25:s0:c512,c768 tcontext=u:object_r:sysfs_kgsl:s0 tclass=dir permissive=0
E iGraphics: failed to load file: /product/etc/xml/igraphics_config_cust.xml
I iGraphics: [0030080c] opt app: 0
I OpenGLRenderer: Initialized EGL, version 1.4
D OpenGLRenderer: Swap behavior 2
W Adreno-ES20: <get_gpu_clk:229>: open failed: errno 13
W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:612>: EGL_BAD_ATTRIBUTE
E vndksupport: Could not load vendor/lib/egl/libGLES_mali.so from sphal namespace: dlopen failed: library "vendor/lib/egl/libGLES_mali.so" not found.
W InputMethodManager: startInputReason = 1
W InputMethodManager: startInputReason = 5
I hwaps   : JNI_OnLoad
W Settings: mValues not put! needsGenerationTracker: true currentGeneration: -1 name: enable_navbar value: null
I zygote  : Do partial code cache collection, code=28KB, data=30KB
I zygote  : After code cache collection, code=28KB, data=30KB
I zygote  : Increasing code cache capacity to 128KB
D KeyEvent: obtain, mHwFlags=96
D KeyEvent: obtain, mHwFlags=96
D ActivityThread: Remove activity client record, r= ActivityRecord{2110b53 token=android.os.BinderProxy@ffad773 {ua.pp.varto/org.qtproject.qt5.android.bindings.QtActivity}} token= android.os.BinderProxy@ffad773
E System  : Uncaught exception thrown by finalizer
E System  : java.lang.AssertionError: Failed to close dex file in finalizer.
E System  : 	at dalvik.system.DexFile.finalize(DexFile.java:336)
E System  : 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:253)
E System  : 	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:240)
E System  : 	at java.lang.Daemons$Daemon.run(Daemons.java:103)
E System  : 	at java.lang.Thread.run(Thread.java:784)
```

**Comment by Kyeiv** [comment]
@sevketk have you solved your problem? i am struggling with similar one.
